#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include "hyperdht/compact.hpp"

using namespace hyperdht::compact;

// ---------------------------------------------------------------------------
// Helper: hex string → byte vector
// ---------------------------------------------------------------------------
static std::vector<uint8_t> from_hex(const std::string& hex) {
    std::vector<uint8_t> bytes;
    bytes.reserve(hex.size() / 2);
    for (size_t i = 0; i < hex.size(); i += 2) {
        uint8_t hi = (hex[i] >= 'a') ? (hex[i] - 'a' + 10) : (hex[i] - '0');
        uint8_t lo = (hex[i + 1] >= 'a') ? (hex[i + 1] - 'a' + 10) : (hex[i + 1] - '0');
        bytes.push_back((hi << 4) | lo);
    }
    return bytes;
}

static std::string to_hex(const std::vector<uint8_t>& bytes) {
    static const char digits[] = "0123456789abcdef";
    std::string result;
    result.reserve(bytes.size() * 2);
    for (auto b : bytes) {
        result += digits[b >> 4];
        result += digits[b & 0xF];
    }
    return result;
}

// Helper: encode a value and return hex
template <typename Enc, typename T>
static std::string encode_hex(const T& v) {
    State s;
    Enc::preencode(s, v);
    std::vector<uint8_t> buf(s.end);
    s.buffer = buf.data();
    s.start = 0;
    Enc::encode(s, v);
    return to_hex(buf);
}

// ===========================================================================
// Cross-tests: C++ encode must produce identical bytes to JS encode
// Vectors generated by test/js/generate_test_vectors.js
// ===========================================================================

TEST(CrossVarint, MatchesJS) {
    struct Case { uint64_t value; std::string hex; };
    std::vector<Case> cases = {
        {0,            "00"},
        {1,            "01"},
        {42,           "2a"},
        {252,          "fc"},
        {253,          "fdfd00"},
        {255,          "fdff00"},
        {256,          "fd0001"},
        {4200,         "fd6810"},
        {65535,        "fdffff"},
        {65536,        "fe00000100"},
        {300000,       "fee0930400"},
        {4294967295,   "feffffffff"},
    };

    for (const auto& c : cases) {
        EXPECT_EQ(encode_hex<Uint>(c.value), c.hex)
            << "varint mismatch for value " << c.value;

        // Also verify decode
        auto bytes = from_hex(c.hex);
        auto s = State::for_decode(bytes.data(), bytes.size());
        auto decoded = Uint::decode(s);
        EXPECT_FALSE(s.error);
        EXPECT_EQ(decoded, c.value) << "decode mismatch for hex " << c.hex;
    }
}

TEST(CrossUint16, MatchesJS) {
    EXPECT_EQ(encode_hex<Uint16>(uint16_t{0}), "0000");
    EXPECT_EQ(encode_hex<Uint16>(uint16_t{0x1234}), "3412");
    EXPECT_EQ(encode_hex<Uint16>(uint16_t{0xFFFF}), "ffff");
}

TEST(CrossUint32, MatchesJS) {
    EXPECT_EQ(encode_hex<Uint32>(uint32_t{0}), "00000000");
    EXPECT_EQ(encode_hex<Uint32>(uint32_t{0xDEADBEEF}), "efbeadde");
}

TEST(CrossBool, MatchesJS) {
    EXPECT_EQ(encode_hex<Bool>(false), "00");
    EXPECT_EQ(encode_hex<Bool>(true), "01");
}

TEST(CrossBuffer, MatchesJS) {
    // Null
    {
        State s;
        Buffer::preencode_null(s);
        std::vector<uint8_t> buf(s.end);
        s.buffer = buf.data();
        s.start = 0;
        Buffer::encode_null(s);
        EXPECT_EQ(to_hex(buf), "00");
    }

    // Non-null: 0xDEADBEEF
    {
        auto payload = from_hex("deadbeef");
        State s;
        Buffer::preencode(s, payload.data(), payload.size());
        std::vector<uint8_t> buf(s.end);
        s.buffer = buf.data();
        s.start = 0;
        Buffer::encode(s, payload.data(), payload.size());
        EXPECT_EQ(to_hex(buf), "04deadbeef");
    }
}

TEST(CrossIpv4Addr, MatchesJS) {
    struct Case { std::string host; uint16_t port; std::string hex; };
    std::vector<Case> cases = {
        {"10.20.30.40",  0x1234, "0a141e283412"},
        {"88.99.3.86",   49737,  "5863035649c2"},
        {"192.168.1.1",  8080,   "c0a80101901f"},
    };

    for (const auto& c : cases) {
        auto addr = Ipv4Address::from_string(c.host, c.port);
        EXPECT_EQ(encode_hex<Ipv4Addr>(addr), c.hex)
            << "ipv4addr mismatch for " << c.host << ":" << c.port;

        // Decode
        auto bytes = from_hex(c.hex);
        auto s = State::for_decode(bytes.data(), bytes.size());
        auto decoded = Ipv4Addr::decode(s);
        EXPECT_FALSE(s.error);
        EXPECT_EQ(decoded.host_string(), c.host);
        EXPECT_EQ(decoded.port, c.port);
    }
}

TEST(CrossIpv4Array, MatchesJS) {
    // Empty array
    {
        std::vector<Ipv4Address> addrs;
        EXPECT_EQ(encode_hex<Ipv4Array>(addrs), "00");
    }

    // Two addresses
    {
        std::vector<Ipv4Address> addrs = {
            Ipv4Address::from_string("192.168.1.1", 8080),
            Ipv4Address::from_string("10.0.0.1", 443),
        };
        EXPECT_EQ(encode_hex<Ipv4Array>(addrs), "02c0a80101901f0a000001bb01");

        // Decode
        auto bytes = from_hex("02c0a80101901f0a000001bb01");
        auto s = State::for_decode(bytes.data(), bytes.size());
        auto decoded = Ipv4Array::decode(s);
        EXPECT_FALSE(s.error);
        ASSERT_EQ(decoded.size(), 2);
        EXPECT_EQ(decoded[0].host_string(), "192.168.1.1");
        EXPECT_EQ(decoded[0].port, 8080);
        EXPECT_EQ(decoded[1].host_string(), "10.0.0.1");
        EXPECT_EQ(decoded[1].port, 443);
    }
}

// ===========================================================================
// IPv6 cross-tests: vectors generated by JS compact-encoding-net
// ===========================================================================

TEST(CrossIpv6Addr, MatchesJS) {
    // Vectors from: node -e "require('compact-encoding-net').ipv6Address"
    struct Case { std::string host; uint16_t port; std::string hex; };
    std::vector<Case> cases = {
        {"2001:db8:0:0:0:0:0:1",              8080,  "20010db8000000000000000000000001901f"},
        {"fe80:0:0:0:0:0:0:1",                443,   "fe800000000000000000000000000001bb01"},
        {"0:0:0:0:0:0:0:1",                   0,     "000000000000000000000000000000010000"},
        {"0:0:0:0:0:0:0:0",                   1234,  "00000000000000000000000000000000d204"},
        {"2001:db8:85a3:0:0:8a2e:370:7334",   49737, "20010db885a3000000008a2e0370733449c2"},
    };

    for (const auto& c : cases) {
        auto addr = Ipv6Address::from_string(c.host, c.port);

        // C++ encode must match JS encode byte-for-byte
        EXPECT_EQ(encode_hex<Ipv6Addr>(addr), c.hex)
            << "ipv6addr encode mismatch for " << c.host << ":" << c.port;

        // C++ decode of JS bytes must produce correct host/port
        auto bytes = from_hex(c.hex);
        auto s = State::for_decode(bytes.data(), bytes.size());
        auto decoded = Ipv6Addr::decode(s);
        EXPECT_FALSE(s.error);
        EXPECT_EQ(decoded.host_string(), c.host)
            << "ipv6addr decode host mismatch for hex " << c.hex;
        EXPECT_EQ(decoded.port, c.port)
            << "ipv6addr decode port mismatch for hex " << c.hex;
    }
}

TEST(CrossIpv6Array, MatchesJS) {
    // Empty array
    {
        std::vector<Ipv6Address> addrs;
        EXPECT_EQ(encode_hex<Ipv6Array>(addrs), "00");
    }

    // Two addresses — hex from JS: c.array(net.ipv6Address).encode(...)
    {
        std::vector<Ipv6Address> addrs = {
            Ipv6Address::from_string("2001:db8::1", 8080),
            Ipv6Address::from_string("fe80::1", 443),
        };
        std::string expected = "0220010db8000000000000000000000001901f"
                               "fe800000000000000000000000000001bb01";
        EXPECT_EQ(encode_hex<Ipv6Array>(addrs), expected);

        // Decode
        auto bytes = from_hex(expected);
        auto s = State::for_decode(bytes.data(), bytes.size());
        auto decoded = Ipv6Array::decode(s);
        EXPECT_FALSE(s.error);
        ASSERT_EQ(decoded.size(), 2u);
        EXPECT_EQ(decoded[0].host_string(), "2001:db8:0:0:0:0:0:1");
        EXPECT_EQ(decoded[0].port, 8080);
        EXPECT_EQ(decoded[1].host_string(), "fe80:0:0:0:0:0:0:1");
        EXPECT_EQ(decoded[1].port, 443);
    }
}
